#!/usr/bin/env python
"""
Usage:
    stager INDIR OUTDIR STAGE

Options:
    INDIR   Input directory

    OUTDIR  Output directory

    STAGE   The stage to execute. Supported stages:
              build - Compile all python sources
              test - Runs the test suite
              crash - Crashes
              fail - Doesn't end successfully
              success - Ends successfully
              loop - Succeeds and sets next stage to loop-1
              loop-N - Succeeds and set next stage to loop-(N+1)
"""
import sys


def main(args):
    # print("STAGER:", args)
    indir, outdir, stage = args[:3]
    if stage == "build":
        import shutil
        import compileall
        shutil.copy2(indir + '/trtl', outdir + '/trtl')
        shutil.copytree(indir + '/turtles', outdir + '/turtles')
        compileall.compile_dir(outdir + '/turtles')
        res = {'next': 'test', 'success': True}
    elif stage == 'test':
        import os
        import subprocess
        subprocess.check_call('pip install nose'.split())
        os.chdir(outdir + '')
        subprocess.check_output('nosetests -w /output --doctest-tests'.split())
        res = {'success': True}
    elif stage == 'loop':
        res = {'next': 'loop-1', 'success': True}
    elif stage.startswith('loop-'):
        n = int(stage.split('-', 1)[-1])
        res = {'next': 'loop-%d' % (n+1), 'success': True}
    elif stage == 'crash':
        raise Exception("Failed on purpose!")
    elif stage == 'fail':
        res = {'next': 'fail', 'success': False}
    elif stage == 'success':
        res = {'success': True}
    else:
        raise Exception("Unsupported stage: " + stage)

    with open(outdir + '/result.json', 'w') as fout:
        import json
        json.dump(res, fout)


if __name__ == '__main__':
    main(sys.argv[1:])
