FROM python:3
RUN echo "turtle:x:%(uid_gid)s::/home/turtle:" >> /etc/passwd && mkdir /home/turtle
COPY stager /home/turtle
RUN pyvenv /home/turtle/py
RUN chown -R %(uid_gid)s /home/turtle
USER turtle
ENTRYPOINT ["python", "/home/turtle/stager", "/input", "/output"]
