#!/bin/bash
set -eu
same=false
[ $(stat -c %i /workspace) = $(stat -c %i /result) ] && same=true
# Do the actual work of the stage
mvn "$1"
# Determine what the next stage should be
case "$1" in
validate)
    next=compile
    ;;
compile)
    next=test
    ;;
test)
    next=package
    [ $same != true ] && cp -r target/surefire-reports /result/
    ;;
package)
    next=install
    ;;
install|deploy|clean)
    next=
    ;;
*)
    echo "Stage $1; UNSUPPORTED"
    exit 1
    ;;
esac
[ -z "$next" ] && exit 0
# Generate the result.json
echo "{\"-s\":\"$next\"}" > /result/result.json