FROM progrium/busybox
RUN opkg-install git bash openssh-client
RUN echo "turtle:x:%(uid_gid)s::/home/turtle:" >> /etc/passwd && mkdir /home/turtle
COPY repo_setup /home/turtle
RUN chown -R %(uid_gid)s /home/turtle
USER turtle
ENTRYPOINT ["/bin/bash", "/home/turtle/repo_setup"]
